"""empty message

Revision ID: 007d3184e48f
Revises: 064daacf2c4d
Create Date: 2017-04-05 11:08:48.990038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007d3184e48f'
down_revision = '064daacf2c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
