"""empty message

Revision ID: 064daacf2c4d
Revises: 7809813aaac2
Create Date: 2017-03-30 15:01:39.096411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064daacf2c4d'
down_revision = '7809813aaac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
